name: Go

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: "**/*.sum"
    - uses: actions/checkout@v4
    - run: go mod verify
    - run: go test ./...

  fuzz-tests:
    name: fuzz tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: "**/*.sum"
    - uses: actions/checkout@v4
    - run: go mod verify
    - run: go mod download
    - run: cd fuzz && go test ./...

  integration-tests:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: "**/*.sum"
    - uses: actions/checkout@v4
    - run: go mod verify
    - run: go mod download
    - run: cd integration && go test ./...

  go-vet:
    name: go vet
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: "**/*.sum"
    - uses: actions/checkout@v4
    - run: go vet ./...
    - run: cd fuzz && go vet ./...
    - run: cd integration && go vet ./...

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: "**/*.sum"
    - uses: actions/checkout@v4
    - uses: golangci/golangci-lint-action@v6
      with:
        version: 'v1.57.2'
    - uses: golangci/golangci-lint-action@v6
      with:
        working-directory: 'fuzz'
        version: 'v1.57.2'
    - uses: golangci/golangci-lint-action@v6
      with:
        working-directory: 'integration'
        version: 'v1.57.2'
