name: govulncheck
on:
  pull_request:
  schedule:
    - cron: '22 10 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...
